name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      # الخطوة 1: سحب أحدث إصدار من الصورة
      - name: Pull Docker image
        run: sudo docker pull bilanox/devops1:latest
      
      # الخطوة 2: تحرير المنفذ 5000 إذا كان قيد الاستخدام
      - name: Free Port 5000 if in use
        run: |
          if sudo lsof -i :5000; then
            echo "Port 5000 is in use. Freeing it..."
            sudo kill -9 $(sudo lsof -t -i :5000)
            echo "Port 5000 has been freed."
          else
            echo "Port 5000 is available."
          fi
      
      # الخطوة 3: حذف الحاوية القديمة إذا كانت موجودة
      - name: Delete Old Docker Container
        run: |
          EXISTING_CONTAINER=$(sudo docker ps -a -q -f "name=devops1-container")
          if [ -n "$EXISTING_CONTAINER" ]; then
            sudo docker rm -f devops1-container
            echo "Old container 'devops1-container' has been removed."
          else
            echo "No existing container found with the name 'devops1-container'."
          fi

      # الخطوة 4: تشغيل الحاوية الجديدة
      - name: Run New Docker Container
        run: |
          sudo docker run -d -p 5000:5000 --name devops1-container bilanox/devops1:latest
          echo "New container 'devops1-container' has been created and is running."
