name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull bilanox/devops1:latest

      # Delete Old Docker container dynamically if it exists
      - name: Delete Old docker container (if exists)
        run: |
          CONTAINER_ID=$(sudo docker ps -a -q --filter ancestor=bilanox/devops1:latest)
          if [ -n "$CONTAINER_ID" ]; then
            sudo docker rm -f $CONTAINER_ID
            echo "Old container removed: $CONTAINER_ID"
          else
            echo "No old container found"
          fi

      # Check if port 5000 is free, then run container
      - name: Check Port Availability
        run: |
          if sudo lsof -i :5000; then
            echo "Port 5000 is in use. Trying a different port."
            sudo docker run -d -p 5001:5000 --name devops1-container bilanox/devops1:latest
          else
            echo "Port 5000 is available. Running the container."
            sudo docker run -d -p 5000:5000 --name devops1-container bilanox/devops1:latest
          fi
