name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Login to Docker Hub
      - name: Login to Docker Hub
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # Build Docker image
      - name: Build the Docker image
        run: docker build -t bilanox/devops1:latest .

      # Push Docker image to Docker Hub
      - name: Push to Docker Hub
        run: docker push bilanox/devops1:latest
